# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/anaconda3\\Library\\inclu

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)**itemsize输出arryay的字节数**

In [12]:
z = np.zeros((10,10))
#print(z)
#print("%d bytes"%(z.size * z.itemsize)) # 第一种打印方法
bytes = z.size * z.itemsize  # 第二种打印方法
print(f"{bytes} bytes")

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [14]:
array = np.empty(10)
print(array)
array[4] = 1
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [17]:
array = np.arange(10,50) # 题目中说显示出的数值是 10 到 49 ，括号中应该为（10，50）
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [18]:
print(array[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [20]:
z = np.arange(0,9).reshape((3,3))
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [23]:
# # .nonzero()返回的是数组中，非零元素的位置。如果是二维数组就是描述非零元素在几行几列 
array = np.array([1,2,0,0,4,0])
print(array)
print(array.nonzero())

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (单位矩阵） (★☆☆) 
(**hint**: np.eye)

In [25]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [27]:
array = np.random.random((3,3,3))
print(array)

[[[0.62618616 0.49061391 0.32103585]
  [0.26109906 0.79406248 0.53583006]
  [0.18630988 0.90550104 0.39903723]]

 [[0.49793717 0.10207685 0.57277018]
  [0.61038346 0.82731105 0.77949376]
  [0.79991731 0.25717029 0.01439005]]

 [[0.35815252 0.27710928 0.02234911]
  [0.08339388 0.08475829 0.05181871]
  [0.7816009  0.51051101 0.87948915]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [32]:
array = np.random.random((10,10))
#print(array)
print(array.max())
print(array.min())

0.9945174271844739
0.006590995452523063


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [35]:
array = np.random.random(30)
#print(array)
print(array.mean())

0.4725233906863245


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
#### 创建一个2d数组，其边界为1，内部为0
(**hint**: array\[1:-1, 1:-1\])

In [45]:
array = np.ones((10,10))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [49]:
array = np.ones((5,5))
#print(array)
#array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
array = np.pad(array, pad_width=1)
#mode为填补类型，即怎样去填补，有“constant”，“edge”等模式，如果为constant模式，就得指定填补的值，如果不指定，则默认填充0
print(array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [50]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal（对角线）(★☆☆) 
(**hint**: np.diag)

In [58]:
array = np.diag(1 + np.arange(4),k=-1) # 详情见帮助 
print(array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern（棋盘图案） (★☆☆) 
(**hint**: array\[::2\])

In [7]:
import numpy as np 
array = np.ones((8,8),dtype = int)
#print(array)
array[::2,1::2] = 0
array[1::2,::2] = 0
print(array)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
#### 考虑一个（6,7,8）形状数组，第100个元素的索引（x，y，z）是多少
(**hint**: np.unravel_index)

In [8]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
#### 使用平铺功能创建棋盘格8x8矩阵
(**hint**: np.tile)

In [19]:
# 方法—— 未使用np.tile
array1 = np.array([0,1,0,1,0,1,0,1])
print(array1)
array2 = np.array([1,0,1,0,1,0,1,0]).reshape(8,1)
print(array2)
array = array1 + array2
array = np.where(array<2,array,0)
print(array)

[0 1 0 1 0 1 0 1]
[[1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [26]:
# 方法二 使用np.tile
array = np.array([[0,1],[1,0]])
print(array)
print("*" * 20)
array1 = np.tile(array,(4,1))
print(array1)
print("*" * 20)
array2 = np.tile(array,(4,4))
print(array2)
# Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
# print(Z)

[[0 1]
 [1 0]]
********************
[[0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]]
********************
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
#### 归一化5x5随机矩阵
(**hint**: (x - mean) / std) std是求标准差

In [35]:
array = np.random.random((5,5))
print(array)
print("*" * 20)
array1 = (array - np.mean(array)) / (np.std(array))
print(array1)

[[0.52973892 0.37373937 0.80734042 0.38771137 0.98863288]
 [0.66116727 0.22225763 0.30580473 0.89593742 0.1748493 ]
 [0.74449868 0.24930933 0.02447695 0.51226224 0.85402582]
 [0.39178568 0.44649418 0.51345543 0.6333362  0.38051683]
 [0.04082624 0.88482059 0.21405577 0.141115   0.14030726]]
********************
[[ 0.24722903 -0.31171952  1.24187899 -0.26165763  1.89145238]
 [ 0.71813861 -0.85448067 -0.55513025  1.55932326 -1.02434535]
 [ 1.01671619 -0.75755406 -1.56313155  0.18460984  1.40915342]
 [-0.24705933 -0.05103803  0.18888505  0.61841952 -0.28743577]
 [-1.50455182  1.51949151 -0.88386802 -1.14521581 -1.14810996]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [41]:
array1 = np.arange(15).reshape((5,3))
print(array1)
print("*" * 20)
array2 = np.arange(6).reshape((3,2))
print(array2)
print("*" * 20)
array = np.dot(array1,array2)
print(array)
print("*" * 20)
print(array.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
********************
[[0 1]
 [2 3]
 [4 5]]
********************
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
********************
(5, 2)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [43]:
array = np.arange(11)
array
array[(3 < array) & (array < 8)] *= -1
print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [51]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [57]:
#Z**Z
#2 << Z >> 2
#Z <- Z
#1j*Z
#Z/1/1
#Z<Z>Z
#  没正确的

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [59]:
print(np.array(0) / np.array(0))
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

nan


C:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
#### 如何将浮点数组从零舍入
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [89]:
array = np.random.uniform(-10,+10,10)
print(array)
print("*" * 50)
print(np.abs(array))
print("*" * 50)
print(np.ceil(np.abs(array)))
print("*" * 50)
print(np.copysign(np.ceil(np.abs(array)), array))


[-8.82046831 -5.68454111  1.56020856  8.78487024 -9.04117343  3.93926773
  7.36722848 -5.03338827  9.89114536  1.75870038]
**************************************************
[8.82046831 5.68454111 1.56020856 8.78487024 9.04117343 3.93926773
 7.36722848 5.03338827 9.89114536 1.75870038]
**************************************************
[ 9.  6.  2.  9. 10.  4.  8.  6. 10.  2.]
**************************************************
[ -9.  -6.   2.   9. -10.   4.   8.  -6.  10.   2.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [90]:
array1 = np.random.randint(0,10,10)
array2 = np.random.randint(0,10,10)
z = np.intersect1d(array1,array2)
print(z)

[3 6 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [88]:
np.datetime64

numpy.datetime64

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f"{yesterday}, {today}, {tomorrow}")

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [97]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
#### 使用5种不同的方法提取随机数组的整数部分
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [24]:
array = np.random.uniform(0,+10,10)
print(array)
print(array - array % 1)
print(np.floor(array))
print(np.ceil(array)-1)
print(array.astype(int))
print(np.trunc(array))

[6.76555339 5.94340745 9.76685522 5.56774212 2.96561396 7.9319617
 7.69597339 9.36061366 5.92960004 7.01164326]
[6. 5. 9. 5. 2. 7. 7. 9. 5. 7.]
[6. 5. 9. 5. 2. 7. 7. 9. 5. 7.]
[6. 5. 9. 5. 2. 7. 7. 9. 5. 7.]
[6 5 9 5 2 7 7 9 5 7]
[6. 5. 9. 5. 2. 7. 7. 9. 5. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [31]:
array = np.zeros((5,5))
array += np.arange(5)
array

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
# 使用生成器的的方法
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1) # numpy.fromiter 方法从可迭代对象中建立 ndarray 对象，返回一维数组
print(Z)

In [38]:
# 未使用生成器的方法
z = np.zeros((10))
for i in range(10):
    z[i] +=i
print(z)
    

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
#### 创建大小为10的矢量，值范围为0到1，0 和 1 均排除在外
(**hint**: np.linspace)

In [63]:
array = np.linspace(0,1,11,endpoint=False)[1:]
print(array)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [77]:
array = np.random.random(10)
#array.sort()
np.sort(array)
print(array)

[0.71766229 0.14263205 0.18483564 0.82457269 0.56485003 0.25646413
 0.78539067 0.74626234 0.83732215 0.82319929]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [78]:
array = np.arange(10)
a = np.add.reduce(array)
print(a)

45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [19]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
print(a)
print(b)
equal = np.allclose(a,b) # allclose是对比每一个元素
print(equal)
equal = np.array_equal(a,b) # 判断两数组是否相等
print(equal)

[0 0 1 0 1]
[0 0 0 1 1]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
#### 使数组不可变
(**hint**: flags.writeable)

In [22]:
z = np.zeros(10)
print(z)
z.flags.writeable = False
#z[1] = 1  #为了本页程序运行方便，暂时注释掉这一句
print(z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
#### 考虑表示笛卡尔坐标的随机10x2矩阵，将其转换为极坐标
(**hint**: np.sqrt, np.arctan2)

In [33]:
array = np.random.randint(0,10,20).reshape((10,2))
x , y = array[:, 0] , array[:, 1]
print(x)
print(y)
print(np.sqrt(x**2 + y**2))
print(np.arctan2(y , x))

[2 4 7 6 7 1 3 3 2 0]
[2 2 1 1 1 8 9 0 8 6]
[2.82842712 4.47213595 7.07106781 6.08276253 7.07106781 8.06225775
 9.48683298 3.         8.24621125 6.        ]
[0.78539816 0.46364761 0.14189705 0.16514868 0.14189705 1.44644133
 1.24904577 0.         1.32581766 1.57079633]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [39]:
array = np.random.random(10)
print(array)
print(array.argmax())
array[array.argmax()] = 0
print(array)

[0.11828277 0.4936007  0.02450586 0.58775756 0.48305973 0.88700773
 0.86572556 0.11387005 0.01078675 0.02790972]
5
[0.11828277 0.4936007  0.02450586 0.58775756 0.48305973 0.
 0.86572556 0.11387005 0.01078675 0.02790972]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
#### 创建具有x和y坐标的结构化数组，它们覆盖[0,1] x [0,1]区域
(**hint**: np.meshgrid)

In [9]:
'''
语法：X,Y = numpy.meshgrid(x, y)
输入的x，y，就是网格点的横纵坐标列向量（非矩阵）
输出的X，Y，就是坐标矩阵。
'''
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(np.linspace(0,1,5))
print('*' * 50)
print(Z)

[0.   0.25 0.5  0.75 1.  ]
**************************************************
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
#### 给定两个数组X和Y，构造柯西矩阵C（Cij = 1 /（xi-yj））
(**hint**: np.subtract.outer)

In [15]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c)) # 矩阵求行列式

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
#### 打印每个标量类型numpy的最小和最大可表示值
(**hint**: np.iinfo, np.finfo, eps)

In [20]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [27]:
np.set_printoptions(threshold=np.inf)
z = np.zeros((16,16))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
#### 如何找到向量中最接近给定标量的值
(**hint**: argmin)

In [39]:
z = np.arange(100)
v = np.random.uniform(0,100) # uniform() 方法将随机生成下一个实数，它在 [x, y] 范围内
print(z)
print('*' * 50)
print(v)
index = (np.abs(z-v)).argmin()
print(z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
**************************************************
48.55689625408196
49


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
#### 创建一个表示位置（x，y）和颜色（r，g，b）的结构化数组
(**hint**: dtype)

In [43]:
mydtype = np.dtype([('xy',[('x', np.int64),
                           ('y', np.int64)]),
                    ('color',[('r', np.int16), 
                              ('g', np.int16), 
                              ('b', np.int16)])])

print(np.ones((3, 2), mydtype))

[[((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))]
 [((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))]
 [((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))]]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
#### 用一个(100,2)的随机向量来表示坐标，计算点到点的距离
(**hint**: np.atleast\_2d, T, np.sqrt)

In [49]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
print(X)
print(Y)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
print('*' * 60)
import scipy
import scipy.spatial
Z = np.random.random((10, 2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.95405992 0.7404209  0.84575175 0.67670727 0.31458825 0.06607642
  0.95615355 0.59012377 0.65529683 0.66170721]]
[[0.10691359 0.29607612 0.12184807 0.83227698 0.66423043 0.80477244
  0.12530624 0.52968636 0.95300777 0.54659435]]
[[0.         0.28534907 0.10933297 0.77658003 0.84824883 1.12938996
  0.01851142 0.55784078 0.89729301 0.52800499]
 [0.28534907 0.         0.20359273 0.53997296 0.562913   0.84469665
  0.27514165 0.27778224 0.66242381 0.26259327]
 [0.10933297 0.20359273 0.         0.73026384 0.75915301 1.03647446
  0.11045595 0.48132913 0.85270131 0.46290581]
 [0.77658003 0.53997296 0.73026384 0.         0.39921151 0.61124997
  0.76019593 0.31473447 0.12261456 0.28607616]
 [0.84824883 0.562913   0.75915301 0.39921151 0.         0.28549989
  0.83788145 0.30662996 0.44662589 0.36651033]
 [1.12938996 0.84469665 1.03647446 0.61124997 0.28549989 0.
  1.11978195 0.59185977 0.60758078 0.64917792]
 [0.01851142 0.27514165 0.11045595 0.76019593 0.83788145 1.11978195
  0.         0.545

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
#### 如何把一个浮点数组直接转换成整数
(**hint**: astype(copy=False))

In [52]:
z = np.arange(10,dtype=np.float32)
print(z)
z =z.astype(np.int32, copy=False)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z = np.genfromtxt(s,delimiter=",")
print(z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [57]:
z = np.arange(9).reshape(3,3)
print(z)
print('*'*50)
for index, value in np.ndenumerate(z):
    print(index, value)
print('*' * 50)
for index in np.ndindex(z.shape):
    print(index,z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
**************************************************
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
**************************************************
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
#### 生成二维高斯分布
(**hint**: np.meshgrid, np.exp)

In [2]:
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D =np.sqrt((X*X+Y*Y))
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2)))

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib widget
fig = plt.figure()
ax= fig.add_subplot(1, 3, 1, projection='3d')
suf=ax.plot_surface(X, Y, G, rstride=1, cstride=1, cmap='rainbow')
fig.colorbar(suf,shrink=0.5, aspect=5)
plt.subplot(132)
suf1 =plt.contourf(X,Y,G,8, alpha=.75, cmap='rainbow')
fig.colorbar(suf1,shrink=0.5, aspect=5)
# plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [10]:
n = 10
p = 3
z = np.zeros((n, n))
np.put(z, np.random.choice(range(n*n), p, replace=False), 1)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
#### 减去矩阵每一行的平均值
(**hint**: mean(axis=,keepdims=))

In [11]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[ 0.12984743 -0.34242535  0.34340842 -0.00064609 -0.17808292  0.13885402
  -0.18979231  0.28491452  0.17333385 -0.35941157]
 [-0.02752239  0.15858744  0.30148717 -0.40895848 -0.22212053  0.0420095
   0.04729659  0.32059773 -0.25407903  0.042702  ]
 [ 0.43247757 -0.30277564 -0.31971529  0.1416994   0.01656008  0.30468136
   0.14313811 -0.38914027 -0.25512888  0.22820357]
 [ 0.33697836  0.21050816 -0.39512178  0.20032661  0.43917428 -0.36941445
   0.25104263 -0.2791128  -0.13977318 -0.25460783]
 [-0.46125606  0.36810705 -0.53188305 -0.14985736  0.02916372 -0.13012611
   0.33177672  0.39368181 -0.23005295  0.38044624]]


#### 59. How to sort an array by the nth column? (★★☆) 
#### 如何按第n列对数组排序
(**hint**: argsort)

In [16]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[8 1 4]
 [5 7 0]
 [9 9 6]]
[[8 1 4]
 [5 7 0]
 [9 9 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
#### 如何判断给定的二维数组是否具有空列
(**hint**: any, ~)

In [70]:
z = np.random.randint(0,3,(3,10))
print(z)
print((~z.any(axis=0)).any())

[[1 1 1 2 2 2 1 0 1 2]
 [0 0 2 0 2 0 0 0 2 0]
 [1 0 1 0 2 0 2 2 2 0]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
#### 从数组中的给定值中找到最接近的值
(**hint**: np.abs, argmin, flat)

In [73]:
a = np.random.uniform(0,1,10)
print(a)
b = 0.5
print(np.abs(a-b).argmin())
m = a.flat[np.abs(a - b).argmin()] #flat返回的是一个迭代器，可以用for访问数组每一个元素
print(m)                           ##可以用索引对迭代器进行引号a.flat[3]

[0.10950544 0.92247323 0.60056353 0.17503235 0.41204071 0.356318
 0.19633221 0.82076589 0.10527292 0.38833076]
4
0.4120407137210734


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
#### 考虑两个形状为（1,3）和（3,1）的数组，如何使用迭代器计算它们的和
(**hint**: np.nditer)

In [78]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
it  =np.nditer([a,b,None])
for x, y, z in it: z[...] = x + y
print(x,y,z)
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
2 2 4
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
#### 创建一个具有名称属性的数组类
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [84]:
z = np.ones(10)
print(z)
i = np.random.randint(0,len(z),10)
print(i)
z += np.bincount(i, minlength=len(z))
print(np.bincount(i, minlength=len(z)))
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4 9 6 8 2 9 5 9 6 5]
[0 0 1 0 1 2 2 0 1 3]
[1. 1. 2. 1. 2. 3. 3. 1. 2. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray | np.unique)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)