# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/anaconda3\\Library\\inclu

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)**itemsize输出arryay的字节数**

In [12]:
z = np.zeros((10,10))
#print(z)
#print("%d bytes"%(z.size * z.itemsize)) # 第一种打印方法
bytes = z.size * z.itemsize  # 第二种打印方法
print(f"{bytes} bytes")

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [14]:
array = np.empty(10)
print(array)
array[4] = 1
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [17]:
array = np.arange(10,50) # 题目中说显示出的数值是 10 到 49 ，括号中应该为（10，50）
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [18]:
print(array[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [20]:
z = np.arange(0,9).reshape((3,3))
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [23]:
# # .nonzero()返回的是数组中，非零元素的位置。如果是二维数组就是描述非零元素在几行几列 
array = np.array([1,2,0,0,4,0])
print(array)
print(array.nonzero())

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (单位矩阵） (★☆☆) 
(**hint**: np.eye)

In [25]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [27]:
array = np.random.random((3,3,3))
print(array)

[[[0.62618616 0.49061391 0.32103585]
  [0.26109906 0.79406248 0.53583006]
  [0.18630988 0.90550104 0.39903723]]

 [[0.49793717 0.10207685 0.57277018]
  [0.61038346 0.82731105 0.77949376]
  [0.79991731 0.25717029 0.01439005]]

 [[0.35815252 0.27710928 0.02234911]
  [0.08339388 0.08475829 0.05181871]
  [0.7816009  0.51051101 0.87948915]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [32]:
array = np.random.random((10,10))
#print(array)
print(array.max())
print(array.min())

0.9945174271844739
0.006590995452523063


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [35]:
array = np.random.random(30)
#print(array)
print(array.mean())

0.4725233906863245


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
#### 创建一个2d数组，其边界为1，内部为0
(**hint**: array\[1:-1, 1:-1\])

In [45]:
array = np.ones((10,10))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [49]:
array = np.ones((5,5))
#print(array)
#array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
array = np.pad(array, pad_width=1)
#mode为填补类型，即怎样去填补，有“constant”，“edge”等模式，如果为constant模式，就得指定填补的值，如果不指定，则默认填充0
print(array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [50]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal（对角线）(★☆☆) 
(**hint**: np.diag)

In [58]:
array = np.diag(1 + np.arange(4),k=-1) # 详情见帮助 
print(array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern（棋盘图案） (★☆☆) 
(**hint**: array\[::2\])

In [7]:
import numpy as np 
array = np.ones((8,8),dtype = int)
#print(array)
array[::2,1::2] = 0
array[1::2,::2] = 0
print(array)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
#### 考虑一个（6,7,8）形状数组，第100个元素的索引（x，y，z）是多少
(**hint**: np.unravel_index)

In [8]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
#### 使用平铺功能创建棋盘格8x8矩阵
(**hint**: np.tile)

In [19]:
# 方法—— 未使用np.tile
array1 = np.array([0,1,0,1,0,1,0,1])
print(array1)
array2 = np.array([1,0,1,0,1,0,1,0]).reshape(8,1)
print(array2)
array = array1 + array2
array = np.where(array<2,array,0)
print(array)

[0 1 0 1 0 1 0 1]
[[1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [26]:
# 方法二 使用np.tile
array = np.array([[0,1],[1,0]])
print(array)
print("*" * 20)
array1 = np.tile(array,(4,1))
print(array1)
print("*" * 20)
array2 = np.tile(array,(4,4))
print(array2)
# Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
# print(Z)

[[0 1]
 [1 0]]
********************
[[0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]]
********************
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
#### 归一化5x5随机矩阵
(**hint**: (x - mean) / std) std是求标准差

In [35]:
array = np.random.random((5,5))
print(array)
print("*" * 20)
array1 = (array - np.mean(array)) / (np.std(array))
print(array1)

[[0.52973892 0.37373937 0.80734042 0.38771137 0.98863288]
 [0.66116727 0.22225763 0.30580473 0.89593742 0.1748493 ]
 [0.74449868 0.24930933 0.02447695 0.51226224 0.85402582]
 [0.39178568 0.44649418 0.51345543 0.6333362  0.38051683]
 [0.04082624 0.88482059 0.21405577 0.141115   0.14030726]]
********************
[[ 0.24722903 -0.31171952  1.24187899 -0.26165763  1.89145238]
 [ 0.71813861 -0.85448067 -0.55513025  1.55932326 -1.02434535]
 [ 1.01671619 -0.75755406 -1.56313155  0.18460984  1.40915342]
 [-0.24705933 -0.05103803  0.18888505  0.61841952 -0.28743577]
 [-1.50455182  1.51949151 -0.88386802 -1.14521581 -1.14810996]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [41]:
array1 = np.arange(15).reshape((5,3))
print(array1)
print("*" * 20)
array2 = np.arange(6).reshape((3,2))
print(array2)
print("*" * 20)
array = np.dot(array1,array2)
print(array)
print("*" * 20)
print(array.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
********************
[[0 1]
 [2 3]
 [4 5]]
********************
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
********************
(5, 2)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [43]:
array = np.arange(11)
array
array[(3 < array) & (array < 8)] *= -1
print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [51]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [57]:
#Z**Z
#2 << Z >> 2
#Z <- Z
#1j*Z
#Z/1/1
#Z<Z>Z
#  没正确的

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [59]:
print(np.array(0) / np.array(0))
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

nan


C:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
#### 如何将浮点数组从零舍入
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [89]:
array = np.random.uniform(-10,+10,10)
print(array)
print("*" * 50)
print(np.abs(array))
print("*" * 50)
print(np.ceil(np.abs(array)))
print("*" * 50)
print(np.copysign(np.ceil(np.abs(array)), array))


[-8.82046831 -5.68454111  1.56020856  8.78487024 -9.04117343  3.93926773
  7.36722848 -5.03338827  9.89114536  1.75870038]
**************************************************
[8.82046831 5.68454111 1.56020856 8.78487024 9.04117343 3.93926773
 7.36722848 5.03338827 9.89114536 1.75870038]
**************************************************
[ 9.  6.  2.  9. 10.  4.  8.  6. 10.  2.]
**************************************************
[ -9.  -6.   2.   9. -10.   4.   8.  -6.  10.   2.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [90]:
array1 = np.random.randint(0,10,10)
array2 = np.random.randint(0,10,10)
z = np.intersect1d(array1,array2)
print(z)

[3 6 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [88]:
np.datetime64

numpy.datetime64

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f"{yesterday}, {today}, {tomorrow}")

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [97]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
#### 使用5种不同的方法提取随机数组的整数部分
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [24]:
array = np.random.uniform(0,+10,10)
print(array)
print(array - array % 1)
print(np.floor(array))
print(np.ceil(array)-1)
print(array.astype(int))
print(np.trunc(array))

[6.76555339 5.94340745 9.76685522 5.56774212 2.96561396 7.9319617
 7.69597339 9.36061366 5.92960004 7.01164326]
[6. 5. 9. 5. 2. 7. 7. 9. 5. 7.]
[6. 5. 9. 5. 2. 7. 7. 9. 5. 7.]
[6. 5. 9. 5. 2. 7. 7. 9. 5. 7.]
[6 5 9 5 2 7 7 9 5 7]
[6. 5. 9. 5. 2. 7. 7. 9. 5. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [31]:
array = np.zeros((5,5))
array += np.arange(5)
array

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
# 使用生成器的的方法
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1) # numpy.fromiter 方法从可迭代对象中建立 ndarray 对象，返回一维数组
print(Z)

In [38]:
# 未使用生成器的方法
z = np.zeros((10))
for i in range(10):
    z[i] +=i
print(z)
    

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
#### 创建大小为10的矢量，值范围为0到1，0 和 1 均排除在外
(**hint**: np.linspace)

In [63]:
array = np.linspace(0,1,11,endpoint=False)[1:]
print(array)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [77]:
array = np.random.random(10)
#array.sort()
np.sort(array)
print(array)

[0.71766229 0.14263205 0.18483564 0.82457269 0.56485003 0.25646413
 0.78539067 0.74626234 0.83732215 0.82319929]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [78]:
array = np.arange(10)
a = np.add.reduce(array)
print(a)

45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [19]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
print(a)
print(b)
equal = np.allclose(a,b) # allclose是对比每一个元素
print(equal)
equal = np.array_equal(a,b) # 判断两数组是否相等
print(equal)

[0 0 1 0 1]
[0 0 0 1 1]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
#### 使数组不可变
(**hint**: flags.writeable)

In [22]:
z = np.zeros(10)
print(z)
z.flags.writeable = False
#z[1] = 1  #为了本页程序运行方便，暂时注释掉这一句
print(z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
#### 考虑表示笛卡尔坐标的随机10x2矩阵，将其转换为极坐标
(**hint**: np.sqrt, np.arctan2)

In [33]:
array = np.random.randint(0,10,20).reshape((10,2))
x , y = array[:, 0] , array[:, 1]
print(x)
print(y)
print(np.sqrt(x**2 + y**2))
print(np.arctan2(y , x))

[2 4 7 6 7 1 3 3 2 0]
[2 2 1 1 1 8 9 0 8 6]
[2.82842712 4.47213595 7.07106781 6.08276253 7.07106781 8.06225775
 9.48683298 3.         8.24621125 6.        ]
[0.78539816 0.46364761 0.14189705 0.16514868 0.14189705 1.44644133
 1.24904577 0.         1.32581766 1.57079633]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [39]:
array = np.random.random(10)
print(array)
print(array.argmax())
array[array.argmax()] = 0
print(array)

[0.11828277 0.4936007  0.02450586 0.58775756 0.48305973 0.88700773
 0.86572556 0.11387005 0.01078675 0.02790972]
5
[0.11828277 0.4936007  0.02450586 0.58775756 0.48305973 0.
 0.86572556 0.11387005 0.01078675 0.02790972]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray | np.unique)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)